#!/usr/bin/env node
/** Regenerate docs/PROJECT_DATA_INVENTORY.md from repo-sync manifest + monorepo index. */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const monorepo = join(root, "..");
const outPath = join(root, "docs/PROJECT_DATA_INVENTORY.md");

const manifestPath = join(monorepo, "CLRTY_SUBSTRATE/boot/prism_repo_sync_manifest.json");
const indexPath = join(monorepo, "manifests/MANIFEST_INDEX.json");

let manifest = { repos: [], prism_cli: {} };
let index = { manifests: [] };

if (existsSync(manifestPath)) {
  manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
}
if (existsSync(indexPath)) {
  index = JSON.parse(readFileSync(indexPath, "utf8"));
}

const lines = [
  "# Project Data Inventory",
  "",
  `Generated: ${new Date().toISOString()}`,
  "",
  "Auto-generated by `scripts/generate_data_inventory.mjs` on verify.",
  "",
  "## Cross-repo pins",
  "",
  "| Slug | URL | SHA |",
  "|------|-----|-----|",
];

for (const repo of manifest.repos ?? []) {
  lines.push(`| ${repo.slug} | ${repo.url} | ${repo.sha ?? repo.ref} |`);
}

if (manifest.prism_cli) {
  lines.push("");
  lines.push(`PRISM CLI: **${manifest.prism_cli.version}** (${manifest.prism_cli.repo}) tag \`${manifest.prism_cli.tag ?? ""}\``);
}

lines.push("", "## Monorepo manifests", "", "| ID | Path |", "|----|------|");
for (const m of index.manifests ?? []) {
  lines.push(`| ${m.id} | \`${m.path}\` |`);
}

lines.push(
  "",
  "## CLI data surfaces",
  "",
  "- `clrt prism sync --repos` — refresh repo-sync manifest",
  "- `clrt pack list` — access packs from wallet-integration",
  "- `clrt registry` — primitive registry browser",
  "- `node scripts/verify_cross_repo.mjs` — cross-repo health",
  ""
);

writeFileSync(outPath, lines.join("\n"));
console.log(`Wrote ${outPath}`);
