#!/usr/bin/env node
/**
 * Sync PRISM terminal Vite env from repo-root .env / process env.
 * Auto-derives VITE_CLRTY_GATE_ACCESS_DIGEST from CLRTY_GATE_MASTER.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const terminalDir = join(root, "apps", "prism-cli");
const terminalEnvPath = join(terminalDir, ".env");
const rootEnvPath = join(root, ".env");
const gateAccessDist = join(root, "packages", "gate-access", "dist", "index.js");

function parseEnvFile(path) {
  const out = {};
  if (!existsSync(path)) return out;
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function env(key, ...sources) {
  for (const src of sources) {
    if (src[key] !== undefined && src[key] !== "") return src[key];
  }
  return process.env[key] ?? "";
}

function ensureGateAccessBuilt() {
  if (existsSync(gateAccessDist)) return;
  console.log("Building @clrt/gate-access for gate env sync…");
  execSync("npm run build -w @clrt/gate-access", { cwd: root, stdio: "inherit" });
}

async function deriveDigest(master) {
  ensureGateAccessBuilt();
  const { deriveGateAccessPassword, digestGateAccessPassword } = await import(
    `file://${gateAccessDist}`
  );
  const password = await deriveGateAccessPassword(master);
  const digest = await digestGateAccessPassword(password);
  return { digest, passwordPreview: `${password.slice(0, 4)}…${password.slice(-4)}` };
}

async function main() {
  const rootEnv = parseEnvFile(rootEnvPath);
  const master = env("CLRTY_GATE_MASTER", rootEnv, process.env);
  const adminPass = env("CLRTY_PRISM_ADMIN_PASS", rootEnv, process.env);
  const publicLaunch = env("VITE_PRISM_TERMINAL_PUBLIC", rootEnv, process.env);

  const lines = [
    "# Auto-generated by scripts/sync_gate_env.mjs — do not commit secrets",
    `# Updated ${new Date().toISOString()}`,
    "",
  ];

  if (master) {
    const { digest, passwordPreview } = await deriveDigest(master);
    lines.push(`VITE_CLRTY_GATE_ACCESS_DIGEST=${digest}`);
    console.log(`Gate env: VITE_CLRTY_GATE_ACCESS_DIGEST set (code ${passwordPreview})`);
  } else {
    console.warn(
      "Gate env: CLRTY_GATE_MASTER not set — personal access codes disabled until you add it to .env"
    );
  }

  if (adminPass) {
    lines.push(`VITE_CLRTY_PRISM_ADMIN_PASS=${adminPass}`);
    console.log("Gate env: VITE_CLRTY_PRISM_ADMIN_PASS set");
  }

  if (publicLaunch) {
    lines.push(`VITE_PRISM_TERMINAL_PUBLIC=${publicLaunch}`);
  }

  lines.push("");
  mkdirSync(terminalDir, { recursive: true });
  writeFileSync(terminalEnvPath, lines.join("\n"));
  console.log(`Wrote ${terminalEnvPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
